// Builds the package.
//
// 1. Generates src/cert.ts from the bundled self-signed certificate in cert/, used for
//    STARTTLS and secureConnection when no credentials are given. It can not be read from
//    disk at run time: the code compiles both as ES module and as CommonJS, and neither
//    __dirname nor import.meta works in both.
// 2. Compiles src/ twice with tsc: once as ES modules into dist/esm and once as CommonJS
//    into dist/cjs. Each output directory gets its own package.json that pins the module
//    format.
// 3. Rewrites the CommonJS modules that have a default export so that `require()` keeps
//    returning the exported function or class itself, the shape the pre-TypeScript CommonJS
//    sources had (`require('imapkit')` is the server factory). Named exports of such a module
//    become properties of the default export (`require('imapkit').TAG_REGEX`), as they were.
// 4. Collects the `@help` lines of the plugins into dist/plugin-help.json for `imapkit --help`.

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tsc = require.resolve('typescript/bin/tsc');

function generateCert() {
    const read = name => fs.readFileSync(path.join(root, 'cert', name), 'utf8');
    const source =
        [
            '// Generated by scripts/build.js from cert/. Do not edit by hand.',
            '',
            '// Self-signed certificate for localhost, used when the server options give no credentials',
            'export const key = ' + JSON.stringify(read('server.key')) + ';',
            'export const cert = ' + JSON.stringify(read('server.crt')) + ';'
        ].join('\n') + '\n';
    writeIfChanged(path.join(root, 'src', 'cert.ts'), source);
}

// Skips the write when the content is already there so that tsc and tsx caches stay warm
function writeIfChanged(target, source) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== source) {
        fs.writeFileSync(target, source);
    }
}

function runTsc(project) {
    const result = spawnSync(process.execPath, [tsc, '-p', project], { cwd: root, stdio: 'inherit' });
    if (result.status !== 0) {
        process.exit(result.status || 1);
    }
}

function listFiles(dir, ext) {
    return fs
        .readdirSync(dir, { recursive: true })
        .filter(name => name.endsWith(ext))
        .map(name => path.join(dir, name));
}

// tsc emits `exports.default = X` for `export default X`. For such modules `require()` returns X
// itself, with the named exports copied onto it and the default export kept as a non-enumerable
// `.default` property, which is what TypeScript and Babel generated `import X from '...'` code reads.
// The copies are made after the module body ran, when every `exports.name = ...` assignment is done.
const DEFAULT_EXPORT_SHIM = `{
    const defaultExport = exports.default;
    if (defaultExport && (typeof defaultExport === 'function' || typeof defaultExport === 'object')) {
        for (const key of Object.keys(exports)) {
            if (key !== 'default' && !(key in defaultExport)) {
                defaultExport[key] = exports[key];
            }
        }
        Object.defineProperty(defaultExport, 'default', { value: defaultExport, enumerable: false, writable: true, configurable: true });
        module.exports = defaultExport;
    }
}
`;

function applyCjsInterop(dir) {
    const defaultExport = /\bexports\.default\s*=/;
    for (const file of listFiles(dir, '.js')) {
        const source = fs.readFileSync(file, 'utf8');
        if (defaultExport.test(source)) {
            fs.writeFileSync(file, source + DEFAULT_EXPORT_SHIM);
        }
    }
}

function writePluginHelp() {
    const dir = path.join(root, 'src', 'plugins');
    const help = {};
    for (const fileName of fs.readdirSync(dir).sort()) {
        if (!fileName.endsWith('.ts') || fileName === 'index.ts') {
            continue;
        }
        const source = fs.readFileSync(path.join(dir, fileName), 'utf8');
        help[fileName.replace(/\.ts$/, '').toUpperCase()] = Array.from(source.matchAll(/@help (.*)/gim), match => match[1]);
    }
    fs.writeFileSync(path.join(root, 'dist', 'plugin-help.json'), JSON.stringify(help, null, 4) + '\n');
}

function build() {
    generateCert();
    fs.rmSync(path.join(root, 'dist'), { recursive: true, force: true });

    runTsc('tsconfig.esm.json');
    runTsc('tsconfig.cjs.json');

    fs.writeFileSync(path.join(root, 'dist', 'esm', 'package.json'), JSON.stringify({ type: 'module' }, null, 4) + '\n');
    fs.writeFileSync(path.join(root, 'dist', 'cjs', 'package.json'), JSON.stringify({ type: 'commonjs' }, null, 4) + '\n');

    applyCjsInterop(path.join(root, 'dist', 'cjs'));
    writePluginHelp();
}

if (process.argv.includes('--generate-only')) {
    generateCert();
} else {
    build();
}
